sports:
  - { "category": "soccer",           "name": "サッカー" }
  - { "category": "icehockey",        "name": "アイスホッケー" }
  - { "category": "baseball",         "name": "野球" }
  - { "category": "basketball",       "name": "バスケ" }
  - { "category": "americanfootball", "name": "アメフト" }
question:
  - "が好きなのはどっち？"
  - "が得意なのはどっち？"
  - "を一緒に見に行きたいのは？"
  - "を愛しているのは？"
  - "をして珍プレーしそうなのは？"
  - "について語り合いたいのは？"
