sports:
  - { "category": "soccer",     "name": "サッカー" }
  - { "category": "icehockey",  "name": "アイスホッケー" }
  - { "category": "baseball",   "name": "野球" }
  - { "category": "basketball", "name": "バスケ" }
  - { "category": "football",   "name": "アメフト" }
  - { "category": "rugby",      "name": "ラグビー" }
  - { "category": "cricket",    "name": "クリケット" }
question:
  - "%sが好きだと思うのはどっち？"
  - "%sが得意だと思うのはどっち？"
  - "%sを一緒に見に行きたいのは？"
  - "%sを愛しているのは？"
  - "%sをして珍プレーしそうなのは？"
  - "%sについて語り合いたいのは？"
