sports:
  - { "category": "soccer",     "name": "Soccer" }
  - { "category": "icehockey",  "name": "IceHockey" }
  - { "category": "baseball",   "name": "Baseball" }
  - { "category": "basketball", "name": "Basketball " }
  - { "category": "football",   "name": "Football" }
  - { "category": "rugby",      "name": "Rugby" }
  - { "category": "cricket",    "name": "Cricket" }
question:
  - "Which person do you think likes %s ?"
  - "Which person do you think is good at playing %s ?"
  - "Which person do you think you want to see %s with ?"
  - "Which person do you think loves %s ?"
  - "Which person do you think you want to talk %s with ?"
